### ISSUE TITLE
Lemma - R (vs webtool)

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/DramaAnalysis#1]
normalisierung in r checken, da andere ergebnisse als auf website

**Comment by nilsreiter** [comment]
Fixed in 31a2cca4.

**Comment by marcuswilland** [comment]
4 Uhr 7 ? 
        Bist du noch ganz sauber?
        
        bzw.: alles in Ordnung?
      
    Am 04.08.2016 um 04:07 schrieb Nils
      Reiter:
    
    
      Fixed in 31a2cca.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/quadrama/DramaAnalysis","title":"quadrama/DramaAnalysis","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/quadrama/DramaAnalysis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nilsreiter in #1: Fixed in 31a2cca4."}],"action":{"name":"View Issue","url":"https://github.com/quadrama/DramaAnalysis/issues/1#issuecomment-237432232"}}}
    
    
    -- 
      Marcus Willand 
      Universität Stuttgart
      Neuere Deutsche Literatur II
      Keplerstr. 17, Zi 2.046
      70174 Stuttgart
      Tel.: 0711-68582784
      marcuswilland.de
