### ISSUE TITLE
dictionaryStatistics(): byFigure=FALSE, segment="Scene"

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#100]
There is an error if you use
`dictionaryStatistics(x, byFigure=FALSE, segment="Scene")` as a setting.

```
Error in merge.data.table(dss, u, by.x = "begin.Scene", by.y = "begin.Scene") : 
  Elements listed in `by.x` must be valid column names in x.
Error during wrapup: cannot open the connection
```

It does work, however, if you use segment="Act".
Tested with: "gdc:n750.0" and "gdc:rksp.0"

**Comment by t-lini** [comment]
Surprisingly, the code from `dictionaryStatistics()` works as it should when executed line by line.

**Comment by nilsreiter** [comment]
`cannot open the connection` maybe indicates that the loading of something didn't work. But you do get the error when executing the function?

**Comment by t-lini** [comment]
Yes, only when executing the function.

**Comment by nilsreiter** [comment]
That was tricky, and I don't really know why. But it works now.

**Comment by BenjaminKrautter** [comment]
sehr schön!

**Comment by nilsreiter** [comment]
Needs to be merged into the develop branch ...
