### ISSUE TITLE
Satzzeichen aus Tokenzählen rausnehmen

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/DramaAnalysis#103]
Hier müssten die Satzzeichen aus der Tokenzählung genommen werden. 
👍

**Comment by nilsreiter** [comment]
Die Funktion `figureStatistics()` müsste eine Option bekommen, dass man Satzzeichen bei der Zählung rauswirft (idealerweise alles was auf `[[:punct:]]` matcht). @TimStrohmayer, könntest Du das übernehmen? Merci :)
