### ISSUE TITLE
dictionaryStatistics(): remove boost-option (not needed anymore)

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#107]
The boost-option appears in the documentation and defaults to 1 in the function definition, but it does not seem to be used anywhere else in the function. Calling the function with another value for boost does not change the output and values of other types such as boost = "test" do not produce errors.

**Comment by nilsreiter** [comment]
I added this option to multiple all values with a constant, but apparently it got removed. Since we don't need it anymore, feel free to remove the argument from the function (and documentation).
