### ISSUE TITLE
function to fetch names of authors and dramas

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#111]
Add function to fetch names of authors and dramas from metadata in order to rename dramas in dataframes (authorname_drama is relevant when working in stylo with frequency tables, for example).

**Comment by t-lini** [comment]
This can be used to rename the ID values in the drama column of a text dataframe into authorname_dramaname or dramaname:
```
renameDramas <- function(t, author=TRUE) {
  dramas <- unique(paste(t$corpus, t$drama, sep=":"))
  meta <- loadMeta(dramas)
  if (author==TRUE) {
    metaSubs <- unique(lapply(meta, function (x) paste(sub("(\\w+).*", "\\1", meta$Name), gsub(" ", "", meta$documentTitle), sep="_")))[[1]]
  } else {
    metaSubs <- unique(lapply(meta, function(x) gsub(" ", "", meta$documentTitle)))[[1]]
  }
  names(metaSubs) <- gsub("\\w+:(.+)","\\1",dramas)
  t$drama <- sapply(t$drama, function(x) metaSubs[x])
  t
}
```

**Comment by nilsreiter** [comment]
This can also be included similarly to the `format.QDHasCharacter()` function, just for the `drama` column. Rename `format.QDHasCharacter()` to `formatCharacterNames.QDHasCharacter()` or have one function with both use cases?

**Comment by nilsreiter** [comment]
I think it's better to have two different functions, the arguments one would need are probably very different.
