### ISSUE TITLE
LimitFigures() und presence()

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#115]
In Abhängigkeit der Zahl der Figuren, die über `limitFigures()` bestimmt werden, verändern sich die `passives` in `presence`. Interessanterweise kann die Zahl der `passives` sowohl zunehmen als auch abnehmen.

Getestet mit:
rksp.0
twt3.0
tzgk.0
r10b.0

**Comment by BenjaminKrautter** [comment]
edit: auch mit `other = TRUE` ergeben sich nicht nachvollziehbare Verschiebungen

**Comment by t-lini** [comment]
`limitFigures()` wirft sämtliche Rede der gefilterten Figuren raus; dass die `passives` also weniger werden können, ist bei der Analyse normal (ebenso, dass Szenen und Akte komplett rausfallen können #116). Hast du ein Beispiel dafür, wo die `passives` mehr werden? Dass für die als `OTHER` auftauchenden Figuren keine `passives` gezählt werden, liegt daran, dass `limitFigures()` die `Mentioned.figure`-Spalten nicht verändert.

Generell ist der Call von `presence()` nach `limitFigures()` etwas problematisch, da nicht das gesamte Drama berücksichtigt wird. Was man wahrscheinlich eher will, ist die `presence`-Tabelle im Sinne von `limitFigures()` zu filtern und nicht die Input-Tabelle. Dafür kann man so vorgehen:
```
t <- rksp.0$mtext
p <- presence(t)
p <- p[figure %in% limitFigures(t)$Speaker.figure_id]
```

**Comment by BenjaminKrautter** [comment]
Ein Beispiel für die Zunahme ist Maria Stuart (twt3.0). Ohne `limitFigures()` hat Maria 13 `passives` und Elisabeth 8 `passives`, auf sieben Figuren limitiert haben beide 15 `passives`.

**Comment by BenjaminKrautter** [comment]
Es ist dann wahrscheinlich generell recht sinnvoll die Figurenlimitierung erst nach der Funktionsausführung auszuführen (etwa bei Segmentierungen wie bei #120).

**Comment by t-lini** [comment]
Die Zunahme hat wahrscheinlich mit der `passiveOnlyWhenNotActive`-Option von `presence`zu tun (per default `True`). Oft ist die Figurenlimitierung nach der Analyse wahrscheinlich sinnvoller, ja.

**Comment by nilsreiter** [comment]
Das ist dann ja auch geklärt, oder?
