### ISSUE TITLE
limitFigures() und scenes

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#116]
Es ist möglich, dass durch `limitFigures` ganze Szenen aus der Analyse fallen, wenn Die Figurenrede aller darin sprechender Figuren entfernt wurde.

**Comment by nilsreiter** [comment]
Ja, weil es Szenen ja eh nur gibt, wenn darin gesprochen wird. Ich weiß nicht wie man das vermeiden kann, wenn wir nicht auf neue Datenstrukturen umsatteln

**Comment by nilsreiter** [comment]
Problem solved in 3.0 :)
