### ISSUE TITLE
Reihenfolge der Figuren

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#117]
Ist es möglich für verschiedene Funktionen, etwa `figureStatistcs`, `dictionaryStatistics`, `utteranceStatistics`, `presence` usw., eine einheitliche Reihenfolge der Figurenauflistung zu schaffen. Manchmal scheint das alphabetisch zu sein, manchmal nach `first begin` geordnet,...

So muss man immer die Farben und IDs tauschen, um grafikübergreifend ein einheitliches Bild zu gewährleisten.

**Comment by t-lini** [comment]
Alphabetisch lässt sich der Output so sortieren:
```
fstat <- figureStatistics(t)
fstat <- fstat[order(fstat$figure),]
```
Wenn einer alphabetischen Sortierung in allen Fällen nichts im Wege steht, lässt sich das im Zuge von #118 auch direkt in die Funktionen einbauen.

**Comment by BenjaminKrautter** [comment]
Fände ich sinnvoll. Alphabetisch ist wahrscheinlich am nachvollziehbarsten.

**Comment by BenjaminKrautter** [comment]
Ich bin mir nicht sicher (zumindest habe ich es nicht hinbekommen), ob der Vorschlag auch mit `configuration()` funktionieren würde. Will man dann bspw. in einer Netzwerkgrafik die Knoten der Figuren gleich gestalten wie in anderen Grafiken (oder man erstellt verschiedene Netzwerke von einzelnen Akten), muss man die Ids immer manuell anpassen.

**Comment by nilsreiter** [comment]
Das kann in 3.0 auch per `format()`-Funktion gemacht werden. Entweder alphabetisch vor- oder rückwärts, oder mit manuell definierter Reihenfolge. Die Funktion frisst alles was eine `character`-Spalte hat, also den Output von `dictionaryStatistics()`, `characterStatistics()`, `configuration()`, ...
