### ISSUE TITLE
Einheitliche Benennung der Figuren

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#118]
Unterschiedliche Funktionen geben unterschiedliche Schreibweisen der Figuren aus

Bsp.:
`pres` -> alle Figuren klein, Unterstrich statt Leerzeichen
`fstat`-> alle Figuren GROß, kein Unterstrich

**Comment by nilsreiter** [comment]
Gibts ne Präferenz was man hier möchte?

**Comment by pagelj** [comment]
Allgemeiner Konsens zur Schreibung war Title Case, also z.B. -> Emilia Galotti, Miss Sara Sampson

**Comment by t-lini** [comment]
Vorschlag: Funktion zum Umwandeln der Spalte`Speaker.figure_id` in Title Case. Diese könnte dann zum Beispiel schon beim Laden der Texte aufgerufen werden. Dann müsste man nur noch die Funktionen abändern, die bisher per default `Speaker.figure_surface` verwenden.

**Comment by nilsreiter** [comment]
An den Figuren-Ids würde ich ungern beim laden was ändern -- die Ids stehen ja womöglich noch in anderen Tabellen. Im report wird diese Funktion
```
toFigureName <- function(x) {
  tools::toTitleCase(tolower(x))
}
```
etabliert, mit der könnte man das relativ leicht bei der Ausgabe machen. Also immer dann wenn wir Plots etc. erzeugen.

**Comment by nilsreiter** [comment]
Denkbar wäre auch, dass wir einen anzeigbaren Namen zentral aus der `Characters`-Tabelle laden

**Comment by nilsreiter** [comment]
Der Unterschied bei `pres` und `fstat` ist übrigens dass im einen Fall die Ids, und im zweiten der Speaker-tag verwendet wird. Für `figureStatistics()` kann man mit `names=TRUE` auch die Verwendung der Namen (= speaker-tags) erzwingen. Für `presence()` gibt es bisher keine Möglichkeit dafür.

**Comment by nilsreiter** [comment]
The solution in 3.0 will be: All functions use character ids. If needed, nice character names can be provided at a central place.

**Comment by nilsreiter** [comment]
This is basically done :)
