### ISSUE TITLE
Segmentierung von Dramenabschnitten

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#120]
Bisher lassen sich die Analysen durch `segment` in Akte und Szenen weiter untergliedern. Will man jedoch Sequenzen betrachten, etwa die Rede einer Figur in den Szenen 5-15, wird es vor allem bei vielen Figuren und Szenen sehr schnell unübersichtlich, weil man immer die entsprechenden "IDs" in der `data.table` raussuchen und dann zusammenführen muss.
Lässt sich das einfacher gestalten? Evtl. könnte man den Funktionen direkt ein Argument beifügen, dass das gewählte `segment` näher spezifiziert und die Reichweite absteckt, etwa `... segment = "act", range = 2:4` für Akt 2 bis 4.

**Comment by t-lini** [comment]
Lässt sich was du meinst damit lösen, dass du die Input-data.table entsprechend subsettest, z.B. so: `t[Number.Act %in% 2:4]` für Akte oder `t[Number.Act == 2 & Number.Scene %in% 2:5]` für Szenen?

**Comment by BenjaminKrautter** [comment]
Ich würde behaupten nur teilweise, da ich so weiterhin das Problem habe, dass die Figurenrede einer Figur X gesplittet wird und für die Akte 2,3 und 4 separat aufgeführt wird. Ich müsste diese also anschließend noch zusammenfügen.

**Comment by t-lini** [comment]
Wenn man nach `t[Number.Act %in% 2:4]` in den Analysen `segment="Drama"` wählt, erhält man ja Analysen zu den zusammengefassten Akten, allerdings ergeben da unter Umständen dann nur noch die absoluten Werte Sinn.

**Comment by BenjaminKrautter** [comment]
Fehler lag bei mir, ich habe die Werte aus `figureStatistics()` als t eingesetzt.

**Comment by nilsreiter** [comment]
D.h. das hier hat sich erledigt? Ich schließe mal.
