### ISSUE TITLE
prepare 3.x for submission into CRAN repository

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#132]
following the steps on [http://r-pkgs.had.co.nz/release.html](http://r-pkgs.had.co.nz/release.html):
- [x] **fix problems with missing visual bindings for global variables and function definitions: use `rlang::.data`**
- [x] **fix that tests work only with `devtools:test()` but not with `devtools:check()`**
- [x] make the package more portable by not using GNU extensions in Makefile?
- [x] decide on version number 
- [x] create `cran-comments.md`(and add it to `.Rbuildignore`)
- [x] document checks on different platforms on R-devel
- [x] manually check CRAN policies
- [x] update/create `README.md`, `NEWS.md`, possibly `README.Rmd`

**Comment by t-lini** [comment]
To prevent notes in R CMD check for global variables/functions, we should probably use `rlang::.data` as suggested [here](https://github.com/STAT545-UBC/Discussion/issues/451#issuecomment-385731301).

**Comment by nilsreiter** [comment]
Makefile is not included in the package
