### ISSUE TITLE
restructure and document loadDramaTEI()

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#136]
(without linguistic features)

**Comment by t-lini** [comment]
+ add dummy xml file for unit testing and as an example for the correct TEI format

**Comment by TimStrohmayer** [comment]
emph-elements are currently not parsed, this needs to be fixed.

**Comment by nilsreiter** [comment]
Not parsed as in "the text in the elements is thrown away" or as in "the text is not handled to be emphasised"?
