### ISSUE TITLE
New function `split()`

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#140]
This is the opposite function of `combine()`, and used to split up a single `QDDrama` object that contains more than one play into a list.

**Comment by t-lini** [comment]
I'm not sure if it's best to implement it as the split-S3-method for class QDDrama, since the documentation for `base::split()` would be misleading. Maybe it is better to have it as a unique function `splitDramas()`?

**Comment by nilsreiter** [comment]
Good question. I didn't know that there is a `base::split()` function.

**Comment by nilsreiter** [comment]
Btw: We can have documentation specific for `split.QDDrama()`, so this would't be a problem. My vote is for keeping it as a generic S3 method.
