### ISSUE TITLE
hamming-visualisation

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#154]
> Die Funktion hamming() bietet die Möglichkeit, den Figurenwechsel entweder anhand der Szenen oder der Akte zu errechnen. Für uns Nutzer macht es aber oft Sinn, die Akte als senkrechte Linien über die Grafik zu legen, genau so wie bei der Visualisierung der Utterances

**Comment by t-lini** [comment]
We could introduce a `QDHamming` class with a plot function that optionally calls `abline()` like this:
```
d <- rjmw.0
h <- hamming(d)
plot(h)
abline(v=cbind(d$segments, nscene=1:nrow(d$segments))[Number.Scene == 1]$nscene - 0.5)
```

**Comment by pagelj** [comment]
@nilsreiter This issue seems to be resolved, right?

**Comment by nilsreiter** [comment]
Yes, I think so.
