### ISSUE TITLE
Issue in presence function with actives

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaAnalysis#157]
There is a strange error in `presence()` with line https://github.com/quadrama/DramaAnalysis/blob/master/R/presence.R#L62:
`conf.active$actives <- rowSums(conf.active[,4:ncol(conf.active)])`

Error:
```
Error in `[.data.frame`(x, , 4:ncol(x), drop = FALSE) : 
  undefined columns selected 
Traceback:
7. stop("undefined columns selected") 
6. `[.data.frame`(x, , 4:ncol(x), drop = FALSE) 
5. x[, 4:ncol(x), drop = FALSE] 
4. as.matrix.data.frame(x[, 4:ncol(x), drop = FALSE], ...) 
3. as.matrix.QDConfiguration(x) 
2. as.matrix(x) 
1. rowSums(conf.active[, 4:ncol(conf.active)])
```

This occurred for `qd:qdjz.0` and `qd:x3cv.0`, but not for any other text tested (around 40)

Running `conf.active[,4:ncol(conf.active)]` seems to work fine, the issue is within `rowSums`

**Comment by nilsreiter** [comment]
This is a consequence of `NA` values in the character column. 

The second line in this snippet:
```r
drama <- loadDrama("ksd1.0", defaultCollection = "qd")
drama$text <- drama$text[!is.na(drama$text$Speaker.figure_id),]
```

can be used as hot fix, but we need a better solution.

**Comment by nilsreiter** [comment]
Added code to `loadDrama()` that checks whether there are `NA` values, display  warning and remove the rows in the `text` table.
