### ISSUE TITLE
Drama length

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#2]
When https://github.com/quadrama/DramaNLP/issues/10 is done, we can now longer count the tokens in the table to get the length of the drama, as some tokens might be present twice (if uttered by multiple figures)

**Comment by marcuswilland** [comment]
good call. other ways to get this data?

**Comment by nilsreiter** [comment]
Yes, some R-scripts need to be rewritten.

(and it's going to be messy)

**Comment by nilsreiter** [comment]
The easiest way out would be add the drama length to the table, next to the drama id.

**Comment by nilsreiter** [comment]
Actually, this is the only way. It's impossible to filter out double tokens on the R-side.

**Comment by nilsreiter** [comment]
Wait until quadrama/webservice#2 is done, then fix R scripts.

**Comment by nilsreiter** [comment]
fixed `make_figure_statistics`

**Comment by nilsreiter** [comment]
Needs fixing: `count_word_fields`.
