### ISSUE TITLE
loadText() returns N.A.-values for columns Speaker.figure_surface and Speaker.figure_id

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#46]
`loadText()` returns NA-values for columns Speaker.figure_surface and Speaker.figure_id

**Comment by nilsreiter** [comment]
1.0.3

**Comment by nilsreiter** [comment]
Speaker empty in Java export

**Comment by nilsreiter** [comment]
CastFigure annotations not present in current data sets. Reprocessing now. Should be solved then.

**Comment by nilsreiter** [comment]
A new data package has been generated. If loaded through `installData()`, we get correct speaker names and ids.
