### ISSUE TITLE
Reporting doesn't honor data directory

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#58]
If a dataDirectory has been set using `setup(dataDirectory=...)`, it's ignored by the `report()`-function.

**Comment by t-lini** [comment]
In Report.rmd, `setup()` is called without arguments (line 22), resetting the dataDirectory.

**Comment by nilsreiter** [comment]
Can we change `setup()`, so that it checks if there is a dataDirectory option set?
