### ISSUE TITLE
Figure Semantics

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#70]
Wünsche:
- [x] mehrere Figuren in ein Balkendiagramm nebeneinander/übereinander(sollte schon funktionieren?)
- [x] alle Figuren vereinen und in einem eigenen Balkendiagramm darstellen 
- [x] ein Wortfeld über verschiedene Szenen/Akte (x-Achse) hinweg darstellen
- [x] dist() grafisch darstellen, am besten aktspezifisch und aktübergreifend: evtl. als Netwerk?

**Comment by nilsreiter** [comment]
> mehrere Figuren in ein Balkendiagramm nebeneinander/übereinander(sollte schon funktionieren?)

Das haben wir heute ausgetüftelt, es sollte nur noch in die Vignette und den report:
```r
fstat <- figureStatistics(rksp.0$mtext)
m <- as.matrix(fstat[,5:10])
rownames(m) <- fstat$figure
barplot(apply(m, 2, function(x) {x/max(x)}), beside=TRUE, legend.text = rownames(m), col=qd.colors)
```

**Comment by nilsreiter** [comment]
> ein Wortfeld über verschiedene Szenen/Akte (x-Achse) hinweg darstellen

Hier müsste mit `dictionaryStatistics()` das gleiche passieren was @TimStrohmayer in #41 mit `frequencyTable()` gemacht hat. 

New issue #71

**Comment by nilsreiter** [comment]
> dist() grafisch darstellen, am besten aktspezifisch und aktübergreifend: evtl. als Netwerk?

Wir wollen eigentlich keine Plotting-Funktionen bauen, die gibt es ja schon. Das könnte auch gut in eine Vignette.

**Comment by nilsreiter** [comment]
Alles da.
