### ISSUE TITLE
Unterschiedliche Szenenzahl Report/Drama und kumulierter Summengrafik

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#76]
Beobachtet bei Miss Sara Sampson. Report-Datei zeigt 44 Szenen an (richtig). Cumsum-Grafik zeigt mehr als 50 Szenen an.

**Comment by nilsreiter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bla](https://trello.com/c/8vfrIJLn/9-bla)

**Comment by nilsreiter** [comment]
In der Funktion `dictionaryStatistics()` wird jeder Akt auf die gleiche (maximale) Szenenzahl "aufgepumpt". Deswegen gibt es in der Grafik für Miß Sara Sampson 55 Szenen (5 x 11).

**Comment by nilsreiter** [comment]
Das gleiche Problem taucht übrigens jetzt bei allem auf was auf `dictionaryStatistics()` aufbaut und nach Szenen einteilt.
