### ISSUE TITLE
GDC Reportdatei/Text laden wdq6.0

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#79]
ID: wdq6.0

Der Text "Die verkehrte Welt" von Ludwig Tieck lässt sich weder mit loadSegmentedText() noch über report() laden.

Fehlermeldung:
`Error in if (any(y[[yintervals[2L]]] - y[[yintervals[1L]]] < 0L)) stop("All entries in column ",  : 
  missing value where TRUE/FALSE needed`

**Comment by nilsreiter** [comment]
Ich nehme an das war mit 2.0.0 vom R-Paket?

**Comment by BenjaminKrautter** [comment]
Unter Pakete steht: 2.1, müsste aber 2.0.1 sein

**Comment by nilsreiter** [comment]
Nein, dann haben wir bei Dir vielleicht eine Vorab-Version installiert.

**Comment by nilsreiter** [comment]
Hm, bei mir geht es in TG und GDC problemlos.

**Comment by nilsreiter** [comment]
Vielleicht aktualisierst Du mal Deine Installation mit `devtools::install_github("quadrama/DramaAnalysis", ref="develop/2.x", build_vignettes = TRUE)`

**Comment by BenjaminKrautter** [comment]
Funktioniert. Danke

**Comment by nilsreiter** [comment]
Das war ja leicht :)
