### ISSUE TITLE
GDC Reportdatei 11g5q.0

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#80]
GDC ID: 11g5q.0
Textgrid ID: 11g9q.0

Faust I von Goethe lässt sich nicht mit report() öffnen.

Fehlermeldung:
`Quitting from lines 287-335 (Report.Rmd) Error in pm$matrix[, i + 1] : subscript out of bounds`

**Comment by nilsreiter** [comment]
@BenjaminKrautter Hast Du bei GDC (`report("gdc:11g5q.0")`) und TG die gleiche Fehlermeldung?

**Comment by BenjaminKrautter** [comment]
@nilsreiter `report("tg:11g9q.0")` gibt die Fehlermeldung:

`Quitting from lines 80-84 (Report.Rmd) 
Error in merge.data.table(fstat, characters, by.x = c("corpus", "drama",  : 
  Elements listed in `by.y` must be valid column names in y.
Quitting from lines 80-84 (Report.Rmd) 
Error during wrapup: cannot open the connection`

**Comment by nilsreiter** [comment]
Es gibt in `gdc:11g5q.0` und `gdc:11g5q.0` keine Akt/Szenen-Einteilung. Ist das inhaltlich korrekt?

Zeilen 287-335 beziehen sich auf den Personalwechsel an Aktgrenzen, ist also nicht verwunderlich dass es da kracht.

**Comment by BenjaminKrautter** [comment]
Nein, das ist nicht korrekt. Mir scheint auch, dass große Teile des Dramas in der gdc-Datei fehlen.

**Comment by nilsreiter** [comment]
Aber in der TG-Datei sind sie da? Kannst Du benennen was fehlt (damit ich es suchen kann)?

**Comment by BenjaminKrautter** [comment]
Jetzt wo ich mir die Datei genauer anschaue, scheint mir eine Verwechslung bzw. Durchmischung der Dateien vorzuliegen.

Die als "Faust. Der Tragödie erster Teil" benannte xml Datei beinhaltet das "Vorspiel auf dem Theater", das als Vorspiel zum Fauststoff gehört. Deshalb wahrscheinlich auch die andere ID. Das Figurenverzeichnis allerdings müsste Faust I entstammen. Im "Vorspiel auf dem Theater" sprechen nur drei Figuren, das Verzeichnis listet aber geschätzt 70 auf.

Faust I scheint also einfach zu fehlen und das "Vorspiel auf dem Theater" scheint mindestens falsch benannt zu sein.

**Comment by nilsreiter** [comment]
Also, der Report sollte in Zukunft durchlaufen, aber bestimmte Teile weglassen.
