### ISSUE TITLE
Fehlermeldung loadAllInstalledIds()

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#81]
Fehlermeldung: `Error in if (data.table::last(parts) == "xmi") { : 
  missing value where TRUE/FALSE needed`

setup() wurde ausgeführt:
`setup(dataDirectory="C:/Users/Benjamin/Desktop/Quadrama/RStudio/QD_DIR") `

Im Ordner QD_DIR liegen die Unterordner "gdc" und "tg", beide haben einen weiteren Unterordner "csv", in dem die csv-Dateien liegen.

Texte mit `loadSegmentedText("gdc: xxxx")` zu laden funktioniert.

**Comment by nilsreiter** [comment]
Ich kann das nicht reproduzieren. Liegen in den Verzeichnissen noch andere Dateien?

**Comment by BenjaminKrautter** [comment]
In `QD_Dir` liegen die Ordner `collections`, `gdc` und `tg`.

`gdc` beinhaltet den Ordner `csv` und eine `README.md`. In `csv` sind nur die .csv Dateien der Dramen drin.

Die Datenstruktur bei `tg` ist identisch.
Das Problem besteht auch noch mit der neuen Version, die Fehlermeldung hat sich jedoch erweitert:
`Error in if (data.table::last(parts) == "xmi") { : 
  missing value where TRUE/FALSE needed
Error during wrapup: cannot open the connection`

**Comment by nilsreiter** [comment]
Könntest Du mal testen ob das mit der master-Version auch passiert? Einmal `devtools::install_github("quadrama/DramaAnalysis", build_vignettes = TRUE)` eingeben und nochmal testen.

**Comment by BenjaminKrautter** [comment]
Ja, gleicher Fehler, nur ohne `error during wrapup: cannot open the connection`

**Comment by nilsreiter** [comment]
Der `error during wrapup ...`  ist ohnehin ein Folgefehler. Vielleicht können wir das mal zusammen anschauen.

**Comment by nilsreiter** [comment]
Fremde Dateien im `qd.datadir` die nicht Dramen sind und in anderer Verzeichnisstruktur liegen sind das Problem.
