### ISSUE TITLE
dictionaryStatistics(): WF und Wörter

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#89]
Wunsch: Möglichkeit zu sehen, welche Wörter aus den einzelnen Wörterbüchern wie häufig aufgerufen werden.
Kann auch gerne in einer separaten Funktion sein und immer nur die Wörter eines auszuwählenden Wortfelds anzeigen, wenn es das einfacher macht.

Idee Nils: Vielleicht wäre es andersrum einfacher: Eine Verteilung der verwendeten Wörter zu erstellen, und die nach Wortfeldern zu filtern

**Comment by nilsreiter** [comment]
Vielleicht kann @TimStrohmayer sich dem mal annehmen :)

**Comment by t-lini** [comment]
Möglicher Input: Text-Dataframe und einzelnes Wortfeld
Möglicher Rückgabewert: Dataframe mit den Spalten Token.surface oder Token.lemma (Option) und der Wortfrequenz. Dazu noch nach Wortfeld und nach gesamtem Text normalisierte Wortfrequenz?
Das ließe sich dann auch einfach auf die Rede einer einzelnen Figur anwenden.

**Comment by nilsreiter** [comment]
Wir haben ja eh schon eine Funktion `frequencytable()` um eine Wort-Frequenz-Matrix (ggf. nach Akt/Szene/Figur/...) zu erzeugen. Vielleicht kann eine neue Funktion diese Tabelle als input nehmen. Rückgabe könnte dann die gleiche Tabelle gefiltert nach Wortfeldern sein.
