### ISSUE TITLE
limitFigures(): add option to merge figures into 'others'

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#90]
Add boolean argument to limitFigures() that allows the figures that would drop out to be summarized into 'others' (speaker.surface and speaker.id)

**Comment by t-lini** [comment]
introduce option to also filter mentioned figure ids and surfaces (so that gossip networks still can be created after filtering with limitFigures())

**Comment by nilsreiter** [comment]
Maybe it would be easier to have this in an additional function and not in `limitFigures()`
