### ISSUE TITLE
Fehler report("gdc:qdhd.0")

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#94]
Für Hofmannsthals der Tod des Tizian (qdhd.0) erhalte ich eine Fehlermeldung im report()

`Quitting from lines 240-251 (Report.Rmd) 
Error in plot.window(xlim, ylim, log = log, ...) : 
  endliche 'xlim' Werte nötig`

Ist ein ziemliches kurzes Drama, lässt sich aber sonst normal laden. Evtl. Probleme mit Akten/Szenen?

**Comment by nilsreiter** [comment]
Gibt es denn Akte und Szenen wie erwartet?

**Comment by BenjaminKrautter** [comment]
Es gibt nur einen Akt und eine Szene

**Comment by nilsreiter** [comment]
Und die Szene ist in dem Akt?

**Comment by BenjaminKrautter** [comment]
Akt und Szene beginnen und enden mit den gleichen Tokens.

**Comment by nilsreiter** [comment]
Hm, die CSV-Daten sehen auch sonst unspektakulär auf. Muss man reinschauen.

**Comment by nilsreiter** [comment]
Ich glaube das Problem ist dass das Stück so kurz ist. Wenn man Figuren mit < 500 Wörtern rauskickt bleibt nur eine übrig

**Comment by nilsreiter** [comment]
Der report könnte generell wohl etwas robuster sein, aber das Ergebnis wird nicht so interessant sein bei so wenigen Wörtern.

**Comment by nilsreiter** [comment]
... und wenn nur eine Figur da ist, kann R keine Z-Scores ausrechnen und deswegen gibt es diese Fehlermeldung. Ist gefixt, ich pushe bald 2.1.
