### ISSUE TITLE
CI broken / base dictionary

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#95]
For some reason, the continuous integration is currently broken.

```
Quitting from lines 115-117 (Word-Field-Analysis.Rmd) 
Error: processing vignette 'Word-Field-Analysis.Rmd' failed with diagnostics:
no lines available in input
Execution halted
```

**Comment by nilsreiter** [comment]
The problem seems to be that we can no longer load data via HTTP while on travis.

**Comment by nilsreiter** [comment]
The main culprit is the function `dictionaryStatistics()` because it loads data from Github. Cannot be executed in examples etc. unfortunately.

**Comment by nilsreiter** [comment]
Solution: include a base dictionary in the distribution and load it.

**Comment by nilsreiter** [comment]
CI disabled until that happens.

**Comment by t-lini** [comment]
> Solution: include a base dictionary in the distribution and load it.

maybe include default wordfields "Famile", "Krieg", "Ratio", "Liebe", "Religion" as base_dictionary.rda in data folder?

**Comment by nilsreiter** [comment]
Yes, that’s what I meant

**Comment by nilsreiter** [comment]
Automatic CI is now re-enabled (so that you can test it properly)

**Comment by nilsreiter** [comment]
It seems this issue is done, right?

**Comment by nilsreiter** [comment]
I fixed the encoding issues by declaring everything as "UTF-8" and added code that recreates the dictionary to `data-raw/create.R` (It's in 16bb2d8). Unfortunately, the tests no longer are fulfilled after the base_dictionary has been recreated. @TimStrohmayer Is there something that you did to the dictionary before saving it? Encoding doesn't seem to be the issue, because it worked before re-creating the .rda file.

**Comment by t-lini** [comment]
I don't know why, but some terms in the old base_dictionary had trailing whitespaces. The tests need to be updated.

**Comment by nilsreiter** [comment]
I updated the included dictionary for the CRAN release to not include any non-UTF8 characters. There is now a file `data-raw/create.R` that can be used to generate the data files. If this is done, tests may need updating.
